### ISSUE TITLE
Decrypt does not work properly

### ISSUE THREAD

**Issue by xxroot** [mvaisakh/android_device_xiaomi_cannon#1]
Decryption does not work properly,Has been stuck decrypting user 0 partition

**Comment by xxroot** [comment]
android_device_xiaomi_cannon-twrp-11

**Comment by mvaisakh** [comment]
This device tree isn't used for recoveries. It has a base twrp tree which was used to fix bugs on the existing twrp tree found at:
https://github.com/gsuzeda/twrp_cannong

**This device tree is used for custom rom (StatixOS) only.**

**Comment by xxroot** [comment]
Thank you for your reply. I will compile and test it
